### ISSUE TITLE
Adjustable # of Turns Simulated

### ISSUE THREAD

**Issue by homu-gamepress** [eight04/mgcm-skill-data#17]
Great job on the sim! Looks pretty feature complete now!

A few things that would be really nice to have:

* A field to change the number of turns simulated (Important for 4cd skill 3).
* In wardrobe, have a button for all CN/EN dresses (Skill Data's Clean Data sheet, column O).
* Is Score calculated damage?

**Comment by eight04** [comment]
> * A field to change the number of turns simulated

I think we can add this to DPT simulator. Should we add it to sub dress simulator?

> (Important for 4cd skill 3).

Could you elaborate?

> * In wardrobe, have a button for all CN/EN dresses

One problem is that it will quickly get outdated if I don't update the repo in 1~2 weeks. Currently, dresses are sorted according to this page: https://appmedia.jp/magicami/3788680. If EN sever also releases dresses by this order, I think users can use Shift-Click to select all EN dresses.

> * Is Score calculated damage?

If you are talking about DPT simulator than yes. It simulates 5 turns and divides the total damage by 5 to get DPT. If you are talking about sub dress simulator than it depends. If you focus on HP than the score is the extra HP you can get from the sub dress.

**Comment by homu-gamepress** [comment]
For DPT Simulator, I think it might be better to change the score to total damage over x turns, with x being adjustable.

This is important with a dress like 2019 Evo Eliza, with her 4-turn cooldown Skill 3. 

If turns are set to 5, her rotation is:
s3-s2-s1-s1-s3

If turns are set to 4, her rotation is:

s3-s2-s1-s1

(this happens in Sinister 5 if she is the slowest attacker in a fast buffer team).
