### ISSUE TITLE
Season 3 Endless damage scaling

### ISSUE THREAD

**Issue by homu-gamepress** [eight04/mgcm-skill-data#31]
old
1 hit = 1x damage
2 hit = 2x damage
3 hit = 3x damage

= hit x damage

new Endless
1 hit = 1x damage
2 hit = 6x damage
3 hit = 11x damage

= ( 5 x hit - 4) x damage

**Comment by eight04** [comment]
Interesting. So the damage of 2nd+ hits will be multiplied by 5?

**Comment by homu-gamepress** [comment]
Yep, basically.

**Comment by eight04** [comment]
We need a new notation to implement this feature. Take miko seira as an example:
https://github.com/eight04/mgcm-skill-data/blob/75a8491540be224ba4c51dba7c7abce130ccb4d4/data/seira.yml#L65
This will be calculated as
```
3.5+3.5*3*5 = 56
```
However the actual damage should be:
```
2 + (3 + 4 + 5)*5 = 62
```
We should probably note those different hits in multiple lines e.g.
```
- 2
  3
  4
  5
```
We can also extend the syntax to work with AoE attack in the future e.g.
```
- 3 *5
  3 *2 aoe
```

**Comment by eight04** [comment]
Another special case is evo ao s3. Something like this?
```yml
- 7.5
  3.75 aoe
  -3.75
```
