### ISSUE TITLE
Extra atk (special atk) discussion

### ISSUE THREAD

**Issue by eight04** [eight04/mgcm-skill-data#6]
@homu-gamepress

I did some tests with ruffian kaori. Here is the record of the first skill according to the original formula:

mod | hp | extraAtk |   | extraAtk/hp | extraAtk/hp*mod
-- | -- | -- | -- | -- | --
1.898537667 | 20127 | 1587.594357 |   | 0.07887883723 | 0.1497544436
1.900061268 | 15623 | 1230.270732 |   | 0.07874740652 | 0.1496248971
1.899329849 | 15429 | 1215.89102 |   | 0.07880556225 | 0.1496777567
1.899010003 | 15429 | 1216.743968 |   | 0.07886084438 | 0.1497575323
1.896978665 | 12941 | 1022.369231 |   | 0.07900233606 | 0.149865746
1.901515453 | 10558 | 830.7544379 |   | 0.07868483026 | 0.1496204207

It seems that we should not separate the ratio and the modifier so the number will be cleaner. Therefore the formula should be:

```
damage = (atk * atk_buff * skill_modifier + extra_stat * dmg_conversion_ratio)
  * other_stuff
```

In this case, `skill_modifier ~= 1.9` and `dmg_conversion_ratio ~= 0.15`

To verify the formula, we need a skill that can modify `skill_modifier` and test whether extra-part will be affected.

Skill 2 and 3:
```
s2: skill_modifier = 0, dmg_conversion_ratio ~= 0.16
s3: skill_modifier = 0, dmg_conversion_ratio ~= 0.30
```

**Comment by homu-gamepress** [comment]
A bit confused about how the formula would work, since 20127 * .15 = 3019, not 1587.594357.

**Comment by eight04** [comment]
The old formula without unrelated stuff:
```
dmg = (atk + extraAtk) * mod
```
New formula:
```
dmg = (atk * mod) + (extraStat * statMod)
```
Therefore:
```
extraStat * statMod = extraAtk * mod
```
With your example:
```
20127 * .15 = 1587.594357 * 1.898537667
```

-----

BTW I'm writing a simulation script which already produced some nice results. I'll push it later.

**Comment by homu-gamepress** [comment]
I see, that makes sense. Thanks for clarifying!

I been collecting data on s2 and s3, and noticed that something odd, it appears that dmg_conversion_ratio aren't .16 and .3, but:

s2 = 0.1632
s3 = 0.306

I noticed that both are factors of 1.02:

s2 = 0.1632 = 0.16 * 1.02
s3 = 0.306 = 0.30 * 1.02

Very strange. One possibility why this might be the case is our assumption for the rng values of statMod are 1.00, 1.01, 1.02, 1.03 instead.

**Comment by homu-gamepress** [comment]
Tested against 1013 defense:

A | HP | Skill 1 Damage Range
-- | -- | :--
1148 |  12563 |  1727, 1745, 1762, 2590C , 2617C, 2643C, 2669C
1384 | 16117 | 2125, 2147, 2168, 2190
1384 | 19981  | 2371, 2396, 2444, 2420
907 | 13066 | 1568, 1584, 1600,  2376C, 2328C
907 | 16764 | 1788, 1807, 1825, 1843

HP | Skill 2 Damage Range
-- | :--
12937 | 881, 890, 899, 1348C, 1361C 
13066 | 917, 1334C, 1348C, 1361C 
16117 | 1108, 1120, 1131, 1645C, 1662C, 1696C  
16764 | 1153 
19981 | 1360, 1374, 1388, 1402, 2040C, 2081C, 2102C  


HP | Skill 3 Damage Range
-- | :--
12937 |  1651, 1668, 1701
13066 | 1667, 1684, 1701, 1718
16117 | 2057, 2078, 2120, 3085C, 3148C
16764 | 2161
19981 |  2550, 2576, 2602, 2628

**Comment by eight04** [comment]
Interesting. Skill 1 also fits better if we multiply the stat with 1.02:

atk | hp | dmg | dmg w/ hp*1.02
-- | -- | -- | --
884 | 12937 | 1540.052467 | 1556.563103
907 | 13066 | 1566.874645 | 1583.549915
1384 | 16117 | 2147.114294 | 2167.683352
907 | 16764 | 1802.850255 | 1824.245037
1384 | 19981 | 2393.682643 | 2419.183069

Maybe it is caused by sabbath buff? Did you get extra 2% HP?

**Comment by homu-gamepress** [comment]
Does Sabbath buff affect test battles? If so, I didn't track it.

**Comment by homu-gamepress** [comment]
You're right! 

1384 A + 19981 HP vs 1013 D

Skill | No bonus | With bonus
:--- | :-- | :--
Skill 1 | 2346, 2394, 2418  | 2371, 2396, 2444, 2420
Skill 2 | 1331, 1347, 1361, 1374 | 1360, 1374, 1388, 1402
Skill 3 | 2500, 2551, 2576 | 2550, 2576, 2602, 2628

I suspect we never noticed it before, because the ATK/DEF bonuses are usual equal and cancel each other out in test battle. We only noticed this because the HP bonus is slightly higher than the ATK/DEF streak bonus. 

![image](https://user-images.githubusercontent.com/54113629/100166931-b4d5ec00-2e72-11eb-9425-c230443cc28e.png)

**Comment by homu-gamepress** [comment]
Added Special ATK Mod (smod) to spreadsheet https://docs.google.com/spreadsheets/d/1N80A2Uz0lQe8COz3e_xWOePh0_RIMq0hYxkgsMv0CWI/edit#gid=1428786078

**Comment by homu-gamepress** [comment]
SR 2019 Lilly seems to scale differently. Any idea on a good way to test HP%?

**Comment by eight04** [comment]
I think it doesn't use extra stat but the damage scales according to hp%:
```
dmg = atk * skill_mod * some_cale_value_based_on_hp% * skill_bonus *...
```

**Comment by homu-gamepress** [comment]
Looks like against bosses, Target HP Bonus skills (KW Seira s3, Shibuya Ao/Eliza s2) reduce the hp multiplier by 20.  

Still quite good against high round s5 bosses though.
